# BBTravis CI configuration file
language: yocto
env:
  global:
  - CPU_REQUIREMENTS=24
  - MEM_REQUIREMENTS=40000
  - DOCKER_IMAGE=forestscribe/docker-buildworker
  matrix:
  - TARGET=qemux86-64
  - TARGET=raspberrypi3
  - TARGET=intel-corei7-64

# Tests running commands
script:
  - title: clean old build
    cmd: rm -rf gdp-src-build/tmp/

  - title: build gdp
    shell: bash
    cmd: |
        source ./init.sh $TARGET
        bitbake -v genivi-dev-platform

  - title: log output deploy directory
    cmd: find gdp-src-build/tmp/deploy

  - title: upload artifacts
    cmd: python artifactory_upload.py

uploads:
- destdir: '%(ART_OUTPUT_URL)s/%(TARGET)s/'
  files:
    - gdp-src-build/tmp/deploy/images/%(TARGET)s/bzImage-%(TARGET)s.bin
    - gdp-src-build/tmp/deploy/images/%(TARGET)s/genivi-dev-platform-%(TARGET)s.ext4
    - gdp-src-build/tmp/deploy/images/%(TARGET)s/genivi-dev-platform-%(TARGET)s.rpi-sdimg
